-- simIGL lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

return function(obj)
    local function wrapFunc(funcName,wrapperGenerator)
        obj[funcName]=wrapperGenerator(obj[funcName])
    end

    wrapFunc('getMesh',function(origFunc)
        return function(...)
            local h,options=checkargsEx(
                {level=1},
                {
                    {type='int'},
                    {type='table',default={}},
                },
                ...
            )
            local _rets={origFunc(h,options)}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('meshBooleanShape',function(origFunc)
        return function(...)
            local handles,op=checkargsEx(
                {level=1},
                {
                    {type='table',item_type='int'},
                    {type='int'},
                },
                ...
            )
            local _rets={origFunc(handles,op)}
            return table.unpack(_rets)
        end
    end)

    wrapFunc('convexHullShape',function(origFunc)
        return function(...)
            local handles=checkargsEx(
                {level=1},
                {
                    {type='table',item_type='int'},
                },
                ...
            )
            local _rets={origFunc(handles)}
            return table.unpack(_rets)
        end
    end)
end
