-- simLDraw lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

return function(obj)
    local function wrapFunc(funcName,wrapperGenerator)
        obj[funcName]=wrapperGenerator(obj[funcName])
    end
end
